# Build customization
builds:
  - id: main
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: freebsd
        goarch: arm64

release:
  github:
    owner: uw-labs
    name: strongbox

archives:
  - builds:
      - main
    format: binary
    files:
      - none*

brews:
  - name: strongbox
    description: Encryption for git users
    homepage: https://github.com/uw-labs/strongbox
    license: LGPL-3.0
    directory: Formula
    repository:
      owner: uw-labs
      name: homebrew-tap
